services:
  flutter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace
      - flutter-pub-cache:/sdks/.pub-cache
      - flutter-gradle-cache:/root/.gradle
    environment:
      CI: "true"
      ANDROID_SDK_ROOT: /opt/android-sdk-linux
      ANDROID_HOME: /opt/android-sdk-linux
      GRADLE_USER_HOME: /root/.gradle
    command: bash

volumes:
  flutter-pub-cache:
  flutter-gradle-cache:
